### ISSUE TITLE
Support 3.12.0

### ISSUE THREAD

**Issue by joergsesterhenn** [arquillian/arquillian-selenium-bom#21]
The current Version of selenium is 3.12.0  - please update the bom.

**Comment by MatousJobanek** [comment]
@joergsesterhenn Thanks for the info. I'll update and release it today.

**Comment by MatousJobanek** [comment]
the new  version has been released and is already in central http://search.maven.org/#artifactdetails%7Corg.jboss.arquillian.selenium%7Cselenium-bom%7C3.12.0%7Cpom
